//REQUERIMENT
export const FETCH_REQUERIMENTS_STARTS = "FETCH_REQUERIMENTS_START";
export const FETCH_REQUERIMENTS_SUCCESS = "FETCH_REQUERIMENTS_SUCCESS";
export const FETCH_REQUERIMENTS_FAIL = "FETCH_REQUERIMENTS_SUCCESS";

//VEHICLE
export const FETCH_VEHICLES_STARTS = "FETCH_VEHICLES_START";
export const FETCH_VEHICLES_SUCCESS = "FETCH_VEHICLES_SUCCESS";
export const FETCH_VEHICLES_FAIL = "FETCH_VEHICLES_SUCCESS";

//USER
export const FETCH_USERS_STARTS = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_SUCCESS";

//TRAVEL
export const SAVE_TRAVEL_STARTS = "SAVE_TRAVEL_STARTS";
export const SAVE_TRAVEL_SUCCESS = "SAVE_TRAVEL_SUCCESS";
export const SAVE_TRAVEL_FAIL = "SAVE_TRAVEL_FAIL";

export const ADD_REQUERIMENT = "ADD_REQUERIMENT";
export const REMOVE_REQUERIMENT = "REMOVE_REQUERIMENT";

export const SET_TYPE = "SET_TYPE";
export const SET_ELEMENT_SELECTED_ID = "SET_ELEMENT_SELECTED_ID";

export const ELEMENT_NOT_USED_ANYMORE = "ELEMENT_NOT_USED_ANYMORE";

export const ADD_USER_TO_ACCEPT = "ADD_USER_TO_ACCEPT";
export const ADD_USER_ACCEPTED = "ADD_USER_ACCEPTED";
export const REMOVE_USER_TO_ACCEPT = "REMOVE_USER_TO_ACCEPT";

//CLEAN
export const CLEAN_ALL = "CLEAN_ALL";
