export const FETCH_REQUERIMENTS_STARTS = "FETCH_REQUERIMENTS_START";
export const FETCH_REQUERIMENTS_SUCCESS = "FETCH_REQUERIMENTS_SUCCESS";
export const FETCH_REQUERIMENTS_FAIL = "FETCH_REQUERIMENTS_SUCCESS";

export const FETCH_VEHICLES_STARTS = "FETCH_VEHICLES_START";
export const FETCH_VEHICLES_SUCCESS = "FETCH_VEHICLES_SUCCESS";
export const FETCH_VEHICLES_FAIL = "FETCH_VEHICLES_SUCCESS";

export const FETCH_USERS_STARTS = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_SUCCESS";
