export const USER = "user";
export const VEHICLE = "vehicle";

//SOCKET
export const SOCKET_VEHICLE_LISTENING_FOR_TRAVEL =
  "VEHICLE_LISTENING_FOR_TRAVEL";
export const SOCKET_USER_LISTENING_FOR_TRAVEL = "USER_LISTENING_FOR_TRAVEL";
export const SOCKET_USER_DISCONNECT = "USER_DISCONNECT";
export const SOCKET_VEHICLE_REMOVE_TRAVELLING_USER =
  "VEHICLE_REMOVE_TRAVELLING_USER";
export const SOCKET_REFRESH_USERS = "REFRESH_USERS";
export const SOCKET_REFRESH_VEHICLES = "REFRESH_VEHICLES";
export const SOCKET_DISCONNECT = "DISCONNECT";
export const SOCKET_CANT_SHARE_VEHICLE = "SOCKET_CANT_SHARE_VEHICLE";
