export const USER = "user";
export const VEHICLE = "vehicle";

//SOCKET
export const SOCKET_VEHICLE_LISTENING_FOR_TRAVEL =
  "VEHICLE_LISTENING_FOR_TRAVEL";
export const SOCKET_USER_LISTENING_FOR_TRAVEL = "USER_LISTENING_FOR_TRAVEL";
export const SOCKET_USER_DISCONNECT = "USER_DISCONNECT";
